language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node

before_script:
  - npm install -g eslint --silent
  - npm install -g eslint-plugin-html eslint-friendly-formatter eslint-plugin-babel eslint-plugin-import eslint-plugin-jsx-a11y --silent
  - npm install -g eslint-config-standard eslint-plugin-standard eslint-plugin-promise --silent
  - npm install -g mocha --silent

install:
  - yarn install

# after_success:
#   - npm run coverage

branches:
  only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish

# services:
#     - docker
# # http://docs.travis-ci.com/user/workers/container-based-infrastructure
# notifications:
#   email:
#     - thedaviddias@gmail.com
