language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node

before_script:
  - npm install -g eslint --silent
  - npm install -g eslint-plugin-html eslint-friendly-formatter eslint-plugin-babel eslint-plugin-import eslint-plugin-jsx-a11y --silent
  - npm install -g eslint-config-standard eslint-plugin-standard eslint-plugin-promise --silent

install:
  - yarn install

after_success:
  - npm run coverage

branches:
  only:
    - master
    - stable

notifications:
  email:
    - thedaviddias@gmail.com
